ignore:
  - GHSA-2r2c-g63r-vccr
  - GHSA-5rrq-pxf6-6jx5
  - GHSA-8fr3-hfg3-gpgp
  - GHSA-cfm4-qjh2-4765
  - GHSA-gf8q-jrpm-jvxq
  - GHSA-rp65-9cf3-cjxr
  - GHSA-w5p7-h5w8-2hfq
  - GHSA-ww39-953v-wcq6
  - GHSA-x4jg-mjrx-434g
  - GHSA-7fh5-64p2-3v2j
  - GHSA-3qc2-v3hp-6cv8
