default: &default
  host: http://freelex.nzsl.vuw.ac.nz
  path: /dnzsl/freelex/publicsearch?xmldump=1
  obscene_path: /dnzsl/freelex/publicsearch?usage=3
  xml: tmp/freelex.xml
  obscene_xml: tmp/freelex_obscene.xml
  public_host: https://nzsl.nz
  asset_host: http://nzsl-assets.vuw.ac.nz/dnzsl/freelex/assets/
  timeout: 120

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
